### ISSUE TITLE
Plugin fails to boot up on Sync 2.18

### ISSUE THREAD

**Issue by hypixus** [OsuSync/OsuDataDistributeRestful#2]
Can't load OsuDataDistribute-Restful, Version=0.3.0.0, Culture=neutral, PublicKeyToken=null (Could not load type 'Sync.Tools.ConfigGUI.GuiLanguageElement' from assembly 'Sync, Version=2.18.0.0, Culture=neutral, PublicKeyToken=null'.)

This is the error message I get. Seeems like it tries to load non-existent or invalid class, preventing from succesfully starting. I know a little about C# so in case you need further data for analysis just ask in this ticket.

**Comment by KedamaOvO** [comment]
I re-uploaded OsuDataDistributeRestful, please re-download [OsuDataDistributeRestful](https://github.com/OsuSync/OsuDataDistributeRestful/releases/download/v0.3.0/OsuDataDistribute-Restful-0.3.0.zip).

**Comment by hypixus** [comment]
Working perfectly fine after re-upload, issue with installation package. Thank you, closing.
