### ISSUE TITLE
Javascript seems not to load up properly

### ISSUE THREAD

**Issue by hypixus** [OsuSync/OsuDataDistributeRestful#3]
I done everything as mentioned in readme, but the method of accessing live counter through webpage does not work at all(404 message), and by filesystem - cyan colored background appears with no content, although everything seems to be downloaded and working by browser's side.
Same results by accessing(after proper modifications in config.ini) http://localhost:10801/rtpp.html, through Firefox, Chrome and Chrome for android.

**Comment by KedamaOvO** [comment]
Please make sure the "html" folder exists. or you can access [this](http://oddr.kedamaovo.moe/rtpp.html).

**Comment by hypixus** [comment]
@KedamaOvO It exists, with all necessary contents.

**Comment by hypixus** [comment]
Here's my config if you find it useful.
``
[Sync.DefaultConfiguration]
Client=
Source=Bilibili
Language=en-US
LoggerFile=Log.txt
EnableViewersChangedNotify=False
EnableGiftChangedNotify=False
CheckUpdateOnStartup=True
MessageManagerDefaultOption=Auto
[Beatmap Suggest Command.BeatmapSuggestPlugin]
EnableInsoMirrorLink=False
OsuApiKey=
SuggestHistoryCapacity=10
[Now Playing.NpFilter]
EnableAdvanceFeature=False
[OsuDataDistributeRestful.SettingIni]
AllowLAN=True
EnableFileHttpServer=True
FileServerRootPath=..\html
ApiPort=10800
FilePort=10801
[Default Plug-ins.BiliBili]
Cookies=
RoomID=
[Default Plug-ins.Twitch]
HostChannelName=
DefaultClientID=esmhw2lcvrgtqw545ourqjwlg7twee
CurrentClientID=
IsUsingCurrentClientID=0
SOAuth=
[Default Plug-ins.DirectOSUIRCBot]
IRCBotName=
IRCBotPasswd=
IRCNick=
[OsuRTDataProvider.SettingIni]
ListenInterval=100
EnableTourneyMode=
TeamSize=
DebugMode=
ForceOsuSongsDirectory=
GameMode=Auto
DisableProcessNotFoundInformation=False
EnableModsChangedAtListening=False
[RealTimePPDisplayer.SettingIni]
TextOutputPath=rtpp{0}.txt
FontName=Segoe UI
PPFontSize=48
HitCountFontSize=24
PPFontColor=#FFFFFFFF
HitCountFontColor=#FFFFFFFF
BackgroundColor=#00FF00FF
WindowHeight=172
WindowWidth=280
SmoothTime=200
FPS=60
OutputMethods=restful
PPFormat=${rtpp}pp
HitCountFormat=${n100}x100 ${n50}x50 ${nmiss}xMiss
RoundDigits=2
DebugMode=False
DisplayHitObject=True
Topmost=True
WindowTextShadow=True
IgnoreTouchScreenDecrease=False
RankingSendPerformanceToChat=False
[OsuLiveStatusPanelPlugin.OsuLiveStatusPanelPlugin]
BeatmapSourcePlugin=ortdp
Width=1920
Height=1080
EnableOutputModPicture=False
OutputModImageFilePath=..\output_mod.png
ModUnitPixel=90
ModUnitOffset=10
ModSortReverse=True
ModDrawReverse=True
ModUse2x=False
ModSkinPath=
ModIsHorizon=True
EnableScaleClipOutputImageFile=True
EnableListenOutputImageFile=True
PPShowJsonConfigFilePath=..\PPShowConfig.json
EnableOutputBackgroundImage=True
OutputBackgroundImageFilePath=..\output_result.png

**Comment by hypixus** [comment]
@KedamaOvO Ironically, the link provided by you works after reinstallation of the whole thing aaplying the same config file. However, I can't get it to work through the html server.

**Comment by hypixus** [comment]
@KedamaOvO OK, everything works from computer's level. How can I make it work on my phone?

**Comment by KedamaOvO** [comment]
Configuration file is no problem. it's work.
Please make sure the html folder is in the same directory as sync.exe.
![](https://image.ibb.co/hA6qgd/QQ_20180702022248.png)

**Comment by hypixus** [comment]
@KedamaOvO it works now, thanks, but I think you accidentally missed my question in last response 😃 How can I make it work on my phone? It displays blacnk cyan background just as pc did before.

**Comment by KedamaOvO** [comment]
* access http://(IP of your pc):10801/rtpp.html?host=(IP of your pc).
* access http://oddr.kedamaovo.moe/rtpp.html?host=(IP of your pc).
e.g.
http://192.168.1.4:10801/rtpp.html?host=192.168.1.4
http://oddr.kedamaovo.moe/rtpp.html?host=192.168.1.4
![](https://image.ibb.co/eVy2Bd/QQ_20180702023233.jpg)

**Comment by hypixus** [comment]
Without the IP tag in the adress I get cyan background both ways.
With it, I get the same through your site and {"code":404} through PC's website.

**Comment by KedamaOvO** [comment]
Sorry, "ip" should be "host".
http://oddr.kedamaovo.moe working,But oddr file server has a bug and he doesn't work.

**Comment by hypixus** [comment]
Many thanks for your support and time, it works like a charm now.
I guess I'll leave this one open until it is fixed, unless it's not possible 😄

**Comment by KedamaOvO** [comment]
I update oddr to 0.3.1, it fixed file server.
And LAN needs to open ports 10800 and 10801 in the firewall. this is [link](https://github.com/OsuSync/OsuDataDistributeRestful/wiki/How-to-open-firewall-ports%3F)

**Comment by hypixus** [comment]
After making an update, version 0.3.1 displays the same issues as #2.
Also, the structure of a new download is different from previous one. User must put DLL in proper directory, that may mislead due to no longer correct instruction in readme.
Finally, the screenshot you provided before contains sensitive data like version of your system updates and hardware data. Please consider removing them 😃

**Comment by hypixus** [comment]
Also, the structure of a new download is different from previous one. User must put DLL in proper directory, that may mislead due to no longer correct instruction in readme.

**Comment by hypixus** [comment]
The screenshot you provided before contains sensitive data like version of your system updates and hardware data. Please consider removing them 😃

**Comment by KedamaOvO** [comment]
Sorry, I uploaded the wrong zip. 
Now available, please [download](https://github.com/OsuSync/OsuDataDistributeRestful/releases/download/v0.3.1/OsuDataDistribute-Restful-0.3.1.zip) again.
Screenshots I will re-edit.

**Comment by hypixus** [comment]
@KedamaOvO 
I noticed you didnt close it, so I'll do it myself now :)
About that screenshot - you may have edited it, but you did not delete its previous version from history - check it out ;)
