### ISSUE TITLE
add more beatmap info

### ISSUE THREAD

**Issue by cyperdark** [OsuSync/OsuDataDistributeRestful#5]
**_Add the following parameters to:_** http://localhost:10800/api/ortdp/beatmap/info

- star
- ar
- od
- cs
- hp
- bpm

_**pp for FC with acc:**_

- pp_95
- pp_96
- pp_97
- pp_98
- pp_99
- pp_100

_**And also to change these parameters depending on the mods**_

**Comment by KedamaOvO** [comment]
> Add the following parameters to: http://localhost:10800/api/ortdp/beatmap/info
> 
> star
> ar
> od
> cs
> hp
> bpm

you can install [OLSP](https://github.com/OsuSync/OsuLiveStatusPanel), and access http://localhost:10800/api/olsp/{map_info}.
e.g. http://localhost:10800/api/olsp/ar

> pp for FC with acc:
>
> pp_95
> pp_96
> pp_97
> pp_98
> pp_99
> pp_100

This is a good idea, I will try to add a new api (/api/rtppd/fcpp/{acc}).

**Comment by KedamaOvO** [comment]
I released 0.4.0 which has already implemented fcpp.
https://github.com/OsuSync/OsuDataDistributeRestful/releases/tag/v0.4.0

**Comment by KedamaOvO** [comment]
Sorry, I released the incorrect dll. please download it again.﻿
