### ISSUE TITLE
Incorrect pp for acc

### ISSUE THREAD

**Issue by cyperdark** [OsuSync/OsuDataDistributeRestful#6]
PP for accuracy is considered wrong, here are examples:
https://i.imgur.com/2vndo0g.png
https://i.imgur.com/NBcJOWU.png
https://i.imgur.com/GhSFRDz.png
Can you fix it?

You can display pp for accuracy on one page, something like this:
http://localhost:10800/api/extra/fcpp/page/1
on it to show pp for accuracy of 100-90%
page/2 89-80%

**Comment by KedamaOvO** [comment]
> PP for accuracy is considered wrong, here are examples:
> https://i.imgur.com/2vndo0g.png
> https://i.imgur.com/NBcJOWU.png
> https://i.imgur.com/GhSFRDz.png
> Can you fix it?

No, Since oppai-ng does not implement the calculation of slider, this results in the pp given by oppai-ng being smaller than the actual pp. 
***Edit: this a bug in ODDR.***

> You can display pp for accuracy on one page, something like this:
> http://localhost:10800/api/extra/fcpp/page/1
> on it to show pp for accuracy of 100-90%
> page/2 89-80%

This doesn't seem to be very useful, and rarely uses so much pp data.

**Comment by cyperdark** [comment]
> No, Since oppai-ng does not implement the calculation of slider, this results in the pp given by oppai-ng being smaller than the actual pp. (Francesco149/oppai-ng#42)

oppai-ng and ojsama between them is such a big difference?
oppai-ng(https://i.imgur.com/2vndo0g.png) ojsama(https://i.imgur.com/EfWBsYW.jpg)
oppai-ng(https://i.imgur.com/NBcJOWU.png) ojsama(https://i.imgur.com/rws6hzl.jpg)
oppai-ng(https://i.imgur.com/GhSFRDz.png) ojsama(https://i.imgur.com/h8Ia5Ba.jpg)

> This doesn't seem to be very useful, and rarely uses so much pp data.

ok. Then you can make one page only with values from 95 to 100%

**Comment by KedamaOvO** [comment]
> > No, Since oppai-ng does not implement the calculation of slider, this results in the pp given by oppai-ng being smaller than the actual pp. ([Francesco149/oppai-ng#42](https://github.com/Francesco149/oppai-ng/issues/42))
> 
> oppai-ng and ojsama between them is such a big difference?
> oppai-ng(https://i.imgur.com/2vndo0g.png) ojsama(https://i.imgur.com/EfWBsYW.jpg)
> oppai-ng(https://i.imgur.com/NBcJOWU.png) ojsama(https://i.imgur.com/rws6hzl.jpg)
> oppai-ng(https://i.imgur.com/GhSFRDz.png) ojsama(https://i.imgur.com/h8Ia5Ba.jpg)
> 

Sorry, I found this to be a bug in ODDR. I will fix it as soon as possible.😥
I will release the new version right away to fix it.

> > This doesn't seem to be very useful, and rarely uses so much pp data.
> 
> ok. Then you can make one page only with values from 95 to 100%

I don't think it's necessary. You can send multiple requests to get fcpp on the client side, and because the server is localhost it doesn't cause a lot of delay.
