### ISSUE TITLE
error 500 in Tourney mode

### ISSUE THREAD

**Issue by l3lackShark** [OsuSync/OsuDataDistributeRestful#7]
errors in:
localhost:10800/api/ortdp/playing/info
localhost:10800/api/ortdp/gameStatus
[Log-2019-11-05@05.10.30.txt](https://github.com/OsuSync/OsuDataDistributeRestful/files/3808890/Log-2019-11-05%4005.10.30.txt)

**Comment by l3lackShark** [comment]
also http://localhost:10800/api/ortdp/playing/players

**Comment by KedamaOvO** [comment]
turn off  TourneyMode.
![image](https://user-images.githubusercontent.com/9410177/68208659-9ce3be00-000c-11ea-9484-05dc695732d2.png)

**Comment by l3lackShark** [comment]
I need this to work in TourneyMode (I'm actually working on tournament mode)

**Comment by KedamaOvO** [comment]
fixed.
https://github.com/OsuSync/OsuDataDistributeRestful/releases/tag/0.6.1

**Comment by l3lackShark** [comment]
Thanks for the fix!
